/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "scribe": [],
    "scribe.postman": [],
    "scribe.openapi": [],
    "telescope": [
        {
            "name": "view",
            "required": false
        }
    ],
    "app": [],
    "todo": [],
    "auth.authenticated": [],
    "auth.login": [],
    "auth.register": [],
    "auth.logout": [],
    "admin.userCount": [],
    "users.index": [],
    "users.store": [],
    "users.show": [
        {
            "name": "user",
            "required": true,
            "binding": "id"
        }
    ],
    "users.update": [
        {
            "name": "user",
            "required": true,
            "binding": "id"
        }
    ],
    "users.destroy": [
        {
            "name": "user",
            "required": true,
            "binding": "id"
        }
    ],
    "todos.index": [],
    "todos.crea": [],
    "todos.completa": [
        {
            "name": "id",
            "required": true
        }
    ],
    "todos.elimina": [
        {
            "name": "id",
            "required": true
        }
    ],
    "storage.local": [
        {
            "name": "path",
            "required": true
        }
    ]
}
}
export {};
