<?php

return [
    'localized' => [
        'it' => [
            'home' => '',
            'login' => 'accedi',
            'register' => 'registrati',
            'logout' => 'esci',
            'user.show' => 'utente',
            'verification.notice' => 'verifica-email',
            'verification.verify' => 'verifica-email/{id}/{hash}',
            'user.update' => 'utente/{id}/aggiorna',
            'admin' => 'admin',
            'admin.dashboard' => 'admin',
            'admin.roles' => 'admin/ruoli',
            'admin.role.show' => 'admin/ruoli/{id}',
            'admin.role.update' => 'admin/ruoli/{id}/aggiorna',
            'admin.users' => 'admin/utenti',
            'admin.user.show' => 'admin/utenti/{id}',
            'admin.user.update' => 'admin/utenti/{id}/aggiorna',
            'admin.user.blocca' => 'admin/utenti/{id}/blocca',
            'admin.user.sblocca' => 'admin/utenti/{id}/sblocca',
            'example.page' => 'pagina-di-esempio',
        ],
        'en' => [
            'home' => '',
            'login' => 'login',
            'register' => 'register',
            'logout' => 'logout',
            'user.show' => 'user',
            'verification.notice' => 'email/verify',
            'verification.verify' => 'email/verify/{id}/{hash}',
            'user.update' => 'user/{id}/update',
            'admin' => 'admin',
            'admin.dashboard' => 'admin',
            'admin.roles' => 'admin/roles',
            'admin.role.show' => 'admin/roles/{id}',
            'admin.role.update' => 'admin/roles/{id}/update',
            'admin.users' => 'admin/users',
            'admin.user.show' => 'admin/users/{id}',
            'admin.user.update' => 'admin/users/{id}/update',
            'admin.user.blocca' => 'admin/users/{id}/blocca',
            'admin.user.sblocca' => 'admin/users/{id}/sblocca',
            'example.page' => 'example-page',
        ],
    ],
];
